### ISSUE TITLE
Running cpp files in terminal for Competitive Programming 

### ISSUE THREAD

**Issue by Dhrooven** [tcmmichaelb139/.dotfiles#2]
I saw your medium article about Neovim and terminal setup for competitive programming. I wanted to ask how do your compile and run your cpp file? Like do you write the gcc command everytime in new terminal window or something like that?

**Comment by tcmmichaelb139** [comment]
I have a Neovim keybind for running a cpp file (`<leader> rr`): the config can be referenced [here](https://github.com/tcmmichaelb139/.dotfiles/blob/main/nvim/.config/nvim/ftplugin/cpp.lua). This keybind will run a script I created called `cr`, see [here](https://github.com/tcmmichaelb139/.dotfiles/blob/main/scripts/.scripts/cr).
