### ISSUE TITLE
VSCode ricing?

### ISSUE THREAD

**Issue by wthrajat** [tcmmichaelb139/.dotfiles#4]
Hey!
By any chance, [the left window here](https://github.com/tcmmichaelb139/.dotfiles/blob/main/assets/desktop-full.png) is your VSCode? If yes, did you install vibrancy and APC customisations? Would love VSCode configs and list of extensions.
Also any noticeable difference in performance or any bugs you noticed?
Thanks a lot. And yes nice sketchybar! :)

**Comment by tcmmichaelb139** [comment]
Thanks for the compliments! That window is actually the note-taking app Obsidian. As for VSCode, I don't use anything other than the Tokyo Night theme.

**Comment by wthrajat** [comment]
Ah yes that's Obsidian. So dumb of me lol. Thanks!
